### ISSUE TITLE
Closing an Opened cell when another cell is open

### ISSUE THREAD

**Issue by giridharvc7** [gloubibou/HHPanningTableViewCell#21] opened 2013-09-05 13:11 UTC
Is it possible to do this?

**Comment by tomerubin2** [comment] 2013-09-15 06:32
I was just about to ask that, it is already behave like that in iOS 6, but not iOS 7.
would be greatly appreciated for iOS 7 support!

**Comment by gloubibou** [comment] 2013-09-15 08:54
Are you compiling against the 7.0 SDK?
HHPanningTableViewCell has several problems with the 7.0 SDK which will require major changes.

I believe it runs fine on iOS 7 when compiled against the 6.1 SDK

**Comment by tomerubin2** [comment] 2013-09-15 09:31
that's too bad... I was manage to close some holes when it came to iOS 7 (like the drawer issue)
but not this one...really driving me nuts :(

**Comment by gloubibou** [comment] 2013-09-18 20:09
The problem is caused by the table view no longer being the immediate parent of the cell.

Implement:
- (UITableView *)superTableView
  {
  UIView *superview = self.superview;
  
  while (superview != nil) {
      if ([superview isKindOfClass:[UITableView class]]) {
          return (id)superview;
      }
  
  ```
  superview = [superview superview];
  ```
  
  }
  
  return nil;
  }

and replace the call to [self superview] with [self superTableView]

Pierre.

**Comment by gloubibou** [comment] 2013-09-29 21:40
Fixed with commit 8b615fd6091cf3e83a1fbc3f4ee641e818cf3a35

**Closed as completed by gloubibou** 2013-09-29 21:40 UTC
