### ISSUE TITLE
Cell separators not shown on iOS7

### ISSUE THREAD

**Issue by mbigatti** [gloubibou/HHPanningTableViewCell#15] opened 2013-06-22 09:29 UTC
Hi! Thank you for sharing the code. 

I'm experimenting with HHPTVC & iOS7 and I noticed that the cell separators are not shown, even in the demo app. Is that an intended behaviour? Have you any suggestions to restore the separators?

Regards,
MB

**Comment by gloubibou** [comment] 2013-06-22 16:54
Hi!

Basically HHPanningTableViewCell has not yet been tested at all with iOS 7
Knowing that iOS currently is only at a very early beta stage, it probably does not yet make much sense to change code to accommodate features or flaws that may still change.

For the time being, you can work around the problem by changing HHPanningTableViewCell.m:561 to
        containerFrame.size.height = cellBounds.size.height - 1.0f;

Best,
Pierre Bernard

**Comment by mbigatti** [comment] 2013-06-22 17:04
thank you for the quick fix and the suggestion. I agree: it is still early to address these types of issues, I'll check again in the following weeks

regards,
MB

**Comment by jeffgorder** [comment] 2013-09-09 13:57
Love your work. I'm wondering if you've given this one any more thought. As it is, either you don't get a separator if you don't add your fix, or you see the background color in the separator during animation (if the background is a color other than darkGray to black.

**Comment by gloubibou** [comment] 2013-09-09 16:03
I hope to get around to updating HHPanningTableViewCell for iOS 7 soon.

There is another issue with is caused by HHPanningTableViewCell moving subviews to a container view for animation. iOS 7 does not seem to like that. This will require major changes. Hopefully the separator will re-appear once I do away with the container view

**Comment by mbigatti** [comment] 2013-09-10 09:57
Hi. Also this approach seems interesting: http://www.teehanlax.com/blog/reproducing-the-ios-7-mail-apps-interface/, but it is not free of issues, as stated here https://github.com/TeehanLax/UITableViewCell-Swipe-for-Options/issues/2

**Comment by gloubibou** [comment] 2013-09-29 21:41
Fixed with commit 8b615fd6091cf3e83a1fbc3f4ee641e818cf3a35

**Closed as completed by gloubibou** 2013-09-29 21:41 UTC
